style:
  tag:
    color: cyan # text color. possible values: https://bit.ly/3gloNNI
    width_percentage: 0 # column width relative to the terminal window
    min_width: 3 # minimum column width as number of characters
  comment:
    color: blue
    width_percentage: 50
    min_width: 0
  snippet:
    color: white
    width_percentage: 50
    min_width: 0

finder:
  command: fzf # equivalent to the --finder option
  # overrides: --tac # equivalent to the --fzf-overrides option
  overrides: '--height 30'
  # overrides_var: --tac # equivalent to the --fzf-overrides-var option

# cheats:
#   paths:
#     - /path/to/some/dir # on unix-like os
#     - F:\\path\\to\\dir # on Windows
# path: /path/to/some/dir # (DEPRECATED) equivalent to the --path option

# search:
# tags: git,!checkout # equivalent to the --tag-rules option

shell:
  # Shell used for shell out. Possible values: bash, zsh, dash, ...
  # For Windows, use `cmd.exe` instead.
  command: bash

  # finder_command: bash # similar, but for fzf's internals
