return {
  {
    "romus204/tree-sitter-manager.nvim",
    commit = "fa63bc63ae08b661843d9976a43becfbd3daf76c",
    pin = true,
    lazy = false,
    config = function()
      require("tree-sitter-manager").setup({
        -- Enable languages
        ensure_installed = {
          "bash",
          "c",
          "cmake",
          "cpp",
          "css",
          "cue",
          "diff",
          "dockerfile",
          "dot",
          "gitcommit",
          "git_config",
          "gitignore",
          "git_rebase",
          "go",
          "gomod",
          "graphql",
          "hcl",
          "helm",
          "html",
          "java",
          "javascript",
          "jinja",
          "jinja_inline",
          "jq",
          "json",
          "lua",
          "make",
          "markdown",
          "mermaid",
          "nginx",
          "powershell",
          "printf",
          "properties",
          "proto",
          "python",
          "regex",
          "requirements",
          "rust",
          "sql",
          "ssh_config",
          "strace",
          "systemtap",
          "terraform",
          "tmux",
          "toml",
          "typescript",
          "udev",
          "vim",
          "vimdoc",
          "xml",
          "zsh",
        },
        -- Enable highlighting
        highlight = true,
      })
    end,
  }
}
